"""Update xuc

Revision ID: 984f8a389fad
Revises: 
Create Date: 2025-08-18 17:07:46.184356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984f8a389fad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sense_object', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_log', schema=None) as batch_op:
        batch_op.drop_column('sense_object')

    # ### end Alembic commands ###
