"""add intensity & duration_min to practice_log

Revision ID: f933b0077e0c
Revises: 984f8a389fad
Create Date: 2025-08-19 10:30:29.430430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f933b0077e0c'
down_revision = '984f8a389fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intensity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duration_min', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_log', schema=None) as batch_op:
        batch_op.drop_column('duration_min')
        batch_op.drop_column('intensity')

    # ### end Alembic commands ###
